#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_renderer/idl/pulse_renderer.idl
// ============================================================================

#include <flecs.h>

#include "pulse_renderer.h"

inline void pulse_renderer_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseCamera> comp(world, "PulseCamera");
        ecs_id(PulseCamera) = comp.id();
        comp.member(ecs_id(ecs_entity_t), "window_entity", 0, offsetof(PulseCamera, window_entity));
        comp.member("fov", &PulseCamera::fov).range(0.001, 179.0);
        comp.member("near_plane", &PulseCamera::near_plane).range(0.001, 10.0);
        comp.member("far_plane", &PulseCamera::far_plane).range(0.01, 4000.0);
        comp.member("orthographic_size", &PulseCamera::orthographic_size).range(0.001, 100.0);
        comp.member("orthographic", &PulseCamera::orthographic);
    }
    {
        flecs::component<PulseLight> comp(world, "PulseLight");
        ecs_id(PulseLight) = comp.id();
        comp.member("color", &PulseLight::color);
    }
    {
        flecs::component<PulseRenderable> comp(world, "PulseRenderable");
        ecs_id(PulseRenderable) = comp.id();
        comp.member("mesh", &PulseRenderable::mesh);
        comp.member("material", &PulseRenderable::material);
    }
}
