version(1)

typedef "bool"
typedef "char"
typedef "float"
typedef "double"
typedef "int8_t"
typedef "int32_t"
typedef "int64_t"
typedef "uint8_t"
typedef "uint16_t"
typedef "uint32_t"
typedef "uint64_t"
typedef "uintptr_t"
typedef "va_list"
typedef "void"
typedef "anyopaque"
typedef "size_t"
typedef "cstring"

--- External types from other modules
typedef "EPulseResult"
typedef "PulseAppId"
typedef "ecs_entity_t"
typedef "pulse_rendergraph_t"
typedef "pulse_renderpass_encoder_t"
typedef "pulse_texture_handle_t"
typedef "pulse_buffer_handle_t"
typedef "pulse_backbuffer_data_t"

--- CGPU types
typedef "ECGPUBackend"
typedef "ECGPUTextureFormat"
typedef "CGPUInstanceId"
typedef "CGPUAdapterId"
typedef "CGPUDeviceId"
typedef "CGPUQueueId"
typedef "CGPURenderPassId"
typedef "CGPUSurfaceId"
typedef "CGPUSwapChainId"
typedef "CGPUTextureViewId"
typedef "CGPUFramebufferId"
typedef "CGPUSemaphoreId"
typedef "CGPUBufferDescriptor"
typedef "CGPUSamplerDescriptor"
typedef "CGPUTextureDescriptor"
typedef "CGPUVertexLayout"
typedef "CGPUBlendStateDescriptor"
typedef "CGPUDepthStateDescriptor"
typedef "CGPURasterizerStateDescriptor"
typedef "ECGPUPrimitiveTopology"

--- From pulse_math.h
typedef "HMM_Vec4" { cname = "HMM_Vec4" }
typedef "HMM_Mat4" { cname = "HMM_Mat4" }

--- Constants
const_value.GraphicsPluginDescVersion { value = "1u" }
const_value.TypeTexture { value = "UINT64_C(0x1000)" }
const_value.TypeGraphicsBuffer { value = "UINT64_C(0x1001)" }
const_value.TypeSampler { value = "UINT64_C(0x1002)" }
const_value.TypeShaderLibrary { value = "UINT64_C(0x1003)" }
const_value.TypeShader { value = "UINT64_C(0x1004)" }
const_value.TypeComputeShader { value = "UINT64_C(0x1005)" }
const_value.TypeMesh { value = "UINT64_C(0x1006)" }
const_value.TypeMaterial { value = "UINT64_C(0x1007)" }

--- Asset handle types (value structs with index+generation)
struct.ShaderHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.ShaderLibraryHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.ComputeShaderHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.MeshHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.TextureHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.GraphicsBufferHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.MaterialHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

struct.SamplerHandle
    .index "uint32_t"
    .generation "uint32_t"
    ()

--- Asset ref types (handle + data ptr)
struct.Shader
    .handle "ShaderHandle"
    .ptr    "*anyopaque"
    ()

struct.ShaderLibrary
    .handle "ShaderLibraryHandle"
    .ptr    "*anyopaque"
    ()

struct.ComputeShader
    .handle "ComputeShaderHandle"
    .ptr    "*anyopaque"
    ()

struct.GraphicsBuffer
    .handle "GraphicsBufferHandle"
    .ptr    "*anyopaque"
    ()

struct.Texture
    .handle "TextureHandle"
    .ptr    "*anyopaque"
    ()

struct.Mesh
    .handle "MeshHandle"
    .ptr    "*anyopaque"
    ()

struct.Material
    .handle "MaterialHandle"
    .ptr    "*anyopaque"
    ()

struct.Sampler
    .handle "SamplerHandle"
    .ptr    "*anyopaque"
    ()

--- Function pointer: render record callback
funcptr.RenderRecordCallback
    "void"
    .app        "PulseAppId"
    .graph      "*pulse_rendergraph_t"
    .userData   "?*anyopaque"

--- Plugin descriptor
struct.GraphicsPluginDesc
    .structSize             "uint32_t"
    .version                "uint32_t"
    .backend                "ECGPUBackend"
    .swapchainFormat        "ECGPUTextureFormat"
    .imageCount             "uint32_t"
    .enableDebugLayer       "bool"
    .enableGpuBasedValidation "bool"
    .enableVsync            "bool"
    .recordCallback         "RenderRecordCallback"
    .recordUserData         "?*anyopaque"
    ()

--- Renderer state (opaque at C API level)
struct.Renderer
    .instance   "CGPUInstanceId"
    .adapter    "CGPUAdapterId"
    .device     "CGPUDeviceId"
    .graphicsQueue "CGPUQueueId"
    .presentQueue "CGPUQueueId"
    .renderPass "CGPURenderPassId"
    .backend    "ECGPUBackend"
    .swapchainFormat "ECGPUTextureFormat"
    .imageCount "uint32_t"
    .frameIndex "uint64_t"
    ()

--- Window surface
struct.Surface
    .instance "CGPUInstanceId"
    .surface  "CGPUSurfaceId"
    ()

--- Window swapchain
struct.Swapchain
    .device                   "CGPUDeviceId"
    .swapchain                "CGPUSwapChainId"
    .backbufferViews          "*CGPUTextureViewId"
    .framebuffers             "*CGPUFramebufferId"
    .imageAvailableSemaphores "*CGPUSemaphoreId"
    .renderFinishedSemaphores "*CGPUSemaphoreId"
    .backbufferCount          "uint32_t"
    .width                    "uint32_t"
    .height                   "uint32_t"
    .currentBackbufferIndex   "uint32_t"
    .backbuffers              "*pulse_backbuffer_data_t"
    .currentBackbuffer        "*pulse_backbuffer_data_t"
    ()

--- Record callback descriptor
struct.RenderRecordCallbackDesc
    .callback  "RenderRecordCallback"
    .userData  "?*anyopaque"
    .priority  "int32_t"
    ()

--- Shader library create desc
struct.ShaderLibraryCreateDesc
    .code     "*const anyopaque"
    .codeSize "uint32_t"
    ()

--- Shader library load desc
struct.ShaderLibraryLoadDesc
    .path "cstring"
    ()

--- Shader property role
enum.ShaderPropertyRole { underscore }
    .Material
    .NonMaterial
    ()

--- Shader property type
enum.ShaderPropertyType { underscore }
    .Unknown
    .Float
    .Float2
    .Float3
    .Float4
    .Int
    .Mat4
    .Texture
    .Sampler
    ()

--- Shader property descriptor
struct.ShaderPropertyDesc
    .name    "cstring"
    .type    "ShaderPropertyType::Enum"
    .role    "ShaderPropertyRole::Enum"
    .set     "uint32_t"
    .binding "uint32_t"
    .offset  "uint32_t"
    .size_   "uint32_t"
    ()

--- Shader create from binary desc
struct.ShaderCreateFromBinaryDesc
    .vsData             "*const anyopaque"
    .vsSize             "uint32_t"
    .fsData             "*const anyopaque"
    .fsSize             "uint32_t"
    .blendDesc          "CGPUBlendStateDescriptor"
    .depthDesc          "CGPUDepthStateDescriptor"
    .rasterizerState    "CGPURasterizerStateDescriptor"
    .propertyCount      "uint32_t"
    .pProperties        "*const ShaderPropertyDesc"
    ()

--- Shader create from file desc
struct.ShaderCreateFromFileDesc
    .vertPath           "cstring"
    .fragPath           "cstring"
    .blendDesc          "CGPUBlendStateDescriptor"
    .depthDesc          "CGPUDepthStateDescriptor"
    .rasterizerState    "CGPURasterizerStateDescriptor"
    .propertyCount      "uint32_t"
    .pProperties        "*const ShaderPropertyDesc"
    ()

--- Compute shader create from binary desc
struct.ComputeShaderCreateFromBinaryDesc
    .csData "*const anyopaque"
    .csSize "uint32_t"
    ()

--- Compute shader create from file desc
struct.ComputeShaderCreateFromFileDesc
    .csPath "cstring"
    ()

--- Buffer create desc
struct.GraphicsBufferCreateDesc
    .desc     "CGPUBufferDescriptor"
    .dataSize "uint64_t"
    .data     "*const anyopaque"
    ()

--- Sampler create desc
struct.SamplerCreateDesc
    .desc "CGPUSamplerDescriptor"
    ()

--- Texture create desc
struct.TextureCreateDesc
    .desc            "CGPUTextureDescriptor"
    .pixelDataSize   "uint64_t"
    .pixelData       "*const anyopaque"
    .generateMipmaps "bool"
    ()

--- Texture load desc
struct.TextureLoadDesc
    .filepath        "cstring"
    .generateMipmaps "bool"
    ()

--- Mesh create from data desc
struct.MeshCreateFromDataDesc
    .vertexCount          "uint32_t"
    .vertexStride         "uint32_t"
    .layout               "CGPUVertexLayout"
    .vertexData           "*const uint8_t"
    .updateVertexDataFromComputeShader "bool"
    .topology             "ECGPUPrimitiveTopology"
    .indexCount           "uint32_t"
    .indexStride          "uint32_t"
    .indexData            "*const uint8_t"
    .updateIndexDataFromComputeShader "bool"
    ()

--- Mesh create dynamic desc
struct.MeshCreateDynamicDesc
    .topology    "ECGPUPrimitiveTopology"
    .layout      "CGPUVertexLayout"
    .indexStride "uint32_t"
    ()

--- Material create desc
struct.MaterialCreateDesc
    .shader "ShaderHandle"
    ()

--- ======== Functions ========

--- Plugin
func.GraphicsPluginDescDefault
    "GraphicsPluginDesc"
    ()

func.AddGraphicsPlugin
    "EPulseResult"
    .app  "PulseAppId"
    .desc "*const GraphicsPluginDesc"
    ()

--- Renderer
func.GetRenderer
    "*const Renderer"
    .app "PulseAppId"
    ()

func.GetSurface
    "*const Surface"
    .app "PulseAppId"
    .entity "ecs_entity_t"
    ()

func.GetSwapchain
    "*const Swapchain"
    .app "PulseAppId"
    .entity "ecs_entity_t"
    ()

--- Render record callbacks
func.AddRenderRecordCallback
    "EPulseResult"
    .app  "PulseAppId"
    .desc "*const RenderRecordCallbackDesc"
    ()

func.RemoveRenderRecordCallback
    "EPulseResult"
    .app      "PulseAppId"
    .callback "RenderRecordCallback"
    ()

func.ImportWindowBackbuffer
    "pulse_texture_handle_t"
    .app           "PulseAppId"
    .graph         "*pulse_rendergraph_t"
    .windowEntity  "ecs_entity_t"
    ()

--- Shader library
func.CreateShaderLibrary
    "ShaderLibraryHandle"
    .app  "PulseAppId"
    .desc "*const ShaderLibraryCreateDesc"
    ()

func.LoadShaderLibrary
    "ShaderLibraryHandle"
    .app  "PulseAppId"
    .desc "*const ShaderLibraryLoadDesc"
    ()

func.AcquireShaderLibrary
    "bool"
    .app    "PulseAppId"
    .handle "ShaderLibraryHandle"
    .outRef "*ShaderLibrary"
    ()

func.ReleaseShaderLibrary
    "void"
    .app "PulseAppId"
    .ref  "*ShaderLibrary"
    ()

--- Shader
func.CreateShaderFromBinary
    "ShaderHandle"
    .app  "PulseAppId"
    .desc "*const ShaderCreateFromBinaryDesc"
    ()

func.CreateShaderFromFile
    "ShaderHandle"
    .app  "PulseAppId"
    .desc "*const ShaderCreateFromFileDesc"
    ()

func.AcquireShader
    "bool"
    .app    "PulseAppId"
    .handle "ShaderHandle"
    .outRef "*Shader"
    ()

func.ReleaseShader
    "void"
    .app "PulseAppId"
    .ref  "*Shader"
    ()

--- Compute shader
func.CreateComputeShaderFromBinary
    "ComputeShaderHandle"
    .app  "PulseAppId"
    .desc "*const ComputeShaderCreateFromBinaryDesc"
    ()

func.CreateComputeShaderFromFile
    "ComputeShaderHandle"
    .app  "PulseAppId"
    .desc "*const ComputeShaderCreateFromFileDesc"
    ()

func.AcquireComputeShader
    "bool"
    .app    "PulseAppId"
    .handle "ComputeShaderHandle"
    .outRef "*ComputeShader"
    ()

func.ReleaseComputeShader
    "void"
    .app "PulseAppId"
    .ref  "*ComputeShader"
    ()

--- Buffer
func.CreateGraphicsBuffer
    "GraphicsBufferHandle"
    .app  "PulseAppId"
    .desc "*const GraphicsBufferCreateDesc"
    ()

func.AcquireGraphicsBuffer
    "bool"
    .app    "PulseAppId"
    .handle "GraphicsBufferHandle"
    .outRef "*GraphicsBuffer"
    ()

func.ReleaseGraphicsBuffer
    "void"
    .app "PulseAppId"
    .ref  "*GraphicsBuffer"
    ()

--- Sampler
func.CreateSampler
    "SamplerHandle"
    .app  "PulseAppId"
    .desc "*const SamplerCreateDesc"
    ()

func.AcquireSampler
    "bool"
    .app    "PulseAppId"
    .handle "SamplerHandle"
    .outRef "*Sampler"
    ()

func.ReleaseSampler
    "void"
    .app "PulseAppId"
    .ref  "*Sampler"
    ()

--- Texture
func.CreateTexture
    "TextureHandle"
    .app  "PulseAppId"
    .desc "*const TextureCreateDesc"
    ()

func.LoadTexture
    "TextureHandle"
    .app  "PulseAppId"
    .desc "*const TextureLoadDesc"
    ()

func.AcquireTexture
    "bool"
    .app    "PulseAppId"
    .handle "TextureHandle"
    .outRef "*Texture"
    ()

func.ReleaseTexture
    "void"
    .app "PulseAppId"
    .ref  "*Texture"
    ()

--- Mesh
func.CreateMeshFromData
    "MeshHandle"
    .app  "PulseAppId"
    .desc "*const MeshCreateFromDataDesc"
    ()

func.CreateMeshDynamic
    "MeshHandle"
    .app  "PulseAppId"
    .desc "*const MeshCreateDynamicDesc"
    ()

func.LoadMesh
    "MeshHandle"
    .app      "PulseAppId"
    .filepath "cstring"
    ()

func.UpdateMeshVertices
    "void"
    .app   "PulseAppId"
    .mesh  "*MeshHandle"
    .data  "*const anyopaque"
    .count "uint32_t"
    ()

func.UpdateMeshIndices
    "void"
    .app   "PulseAppId"
    .mesh  "*MeshHandle"
    .data  "*const anyopaque"
    .count "uint32_t"
    ()

func.AcquireMesh
    "bool"
    .app    "PulseAppId"
    .handle "MeshHandle"
    .outRef "*Mesh"
    ()

func.ReleaseMesh
    "void"
    .app "PulseAppId"
    .ref  "*Mesh"
    ()

--- Material
func.CreateMaterial
    "MaterialHandle"
    .app  "PulseAppId"
    .desc "*const MaterialCreateDesc"
    ()

func.AcquireMaterial
    "bool"
    .app    "PulseAppId"
    .handle "MaterialHandle"
    .outRef "*Material"
    ()

func.ReleaseMaterial
    "void"
    .app "PulseAppId"
    .ref  "*Material"
    ()

--- Material property setters (name-driven, Unity-style)
func.Material.SetFloat4
    "void"
    .name    "cstring"
    .value   "HMM_Vec4"
    ()

func.Material.SetMat4
    "void"
    .name    "cstring"
    .value   "HMM_Mat4"
    ()

func.Material.SetTexture
    "void"
    .name    "cstring"
    .texture "TextureHandle"
    ()

func.Material.SetSampler
    "void"
    .name    "cstring"
    .sampler "SamplerHandle"
    ()

--- Encoder
func.RenderpassEncoderDraw
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .material "Material"
    .mesh     "Mesh"
    ()

func.RenderpassEncoderDrawSubmesh
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .material "Material"
    .mesh     "Mesh"
    .idxCount "uint32_t"
    .firstIdx "uint32_t"
    .vtxCount "uint32_t"
    .firstVtx "uint32_t"
    ()

func.RenderpassEncoderDrawProcedure
    "void"
    .encoder   "*pulse_renderpass_encoder_t"
    .material  "Material"
    .topology  "ECGPUPrimitiveTopology"
    .vertexCount "uint32_t"
    ()

func.RenderpassEncoderDispatch
    "void"
    .encoder      "*pulse_renderpass_encoder_t"
    .computeShader "ComputeShader"
    .x            "uint32_t"
    .y            "uint32_t"
    .z            "uint32_t"
    ()

func.RenderpassEncoderSetGlobalTexture
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .texture  "Texture"
    .set      "uint32_t"
    .binding  "uint32_t"
    ()

func.RenderpassEncoderSetGlobalBuffer
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .buffer   "GraphicsBuffer"
    .set      "uint32_t"
    .binding  "uint32_t"
    ()

func.RenderpassEncoderSetGlobalSampler
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .sampler  "Sampler"
    .set      "uint32_t"
    .binding  "uint32_t"
    ()

func.RenderpassEncoderSetGlobalTextureHandle
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .handle   "pulse_texture_handle_t"
    .set      "uint32_t"
    .binding  "uint32_t"
    ()

func.RenderpassEncoderSetGlobalBufferHandle
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .handle   "pulse_buffer_handle_t"
    .set      "uint32_t"
    .binding  "uint32_t"
    ()

func.RenderpassEncoderSetGlobalBufferOffset
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .handle   "pulse_buffer_handle_t"
    .set      "uint32_t"
    .binding  "uint32_t"
    .offset   "uint64_t"
    .size_    "uint64_t"
    ()

func.RenderpassEncoderSetViewport
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .x        "float"
    .y        "float"
    .width    "float"
    .height   "float"
    .minDepth "float"
    .maxDepth "float"
    ()

func.RenderpassEncoderSetScissor
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .x        "uint32_t"
    .y        "uint32_t"
    .width    "uint32_t"
    .height   "uint32_t"
    ()

func.RenderpassEncoderPushConstants
    "void"
    .encoder  "*pulse_renderpass_encoder_t"
    .shader   "Shader"
    .name     "cstring"
    .data     "*const anyopaque"
    ()

switch_table.ShaderPropertyIsUniform
    .arg            "ShaderPropertyType::Enum"
    .ret            "bool"
    .cases          ({
                        { Float = true },
                        { Float2 = true },
                        { Float3 = true },
                        { Float4 = true },
                        { Int = true },
                        { Mat4 = true },
                    })
    .default        (false)