add_rules("mode.debug", "mode.release", "mode.releasedbg")
set_languages("cxx20", "c11")
set_exceptions("none")
if is_plat("windows") then 
    add_defines("NOMINMAX")
    set_runtimes(is_mode("debug") and "MDd" or "MD")
    add_ldflags("-subsystem:console")
elseif is_plat("android") then
    add_cxflags("-fPIC")
    includes("androidcpp")
    set_runtimes("c++_static")
end

add_cxxflags("/Zc:__cplusplus", "/Zc:preprocessor", {tools = "cl", force = true})

if is_host("windows") and is_plat("android") then
    set_policy("install.strip_packagelibs", false)
end

add_requires("libsdl3", {configs = {sdlmain = false, shared = is_plat("android")}})
add_requires("imgui v1.92.1-docking")
add_requires("mimalloc")
add_requires("enkits")

if is_plat("windows", "linux", "android") then
    option("use_vulkan")
        set_showmenu(true )
        set_default(true)
end

includes("cgpu/xmake.lua")

includes("src/khr/xmake.lua")

includes("dascript/xmake.lua")

target("pulse_app")
    set_kind("static")
    add_includedirs("src/pulse_app/include", {public = true})
    add_headerfiles("src/pulse_app/include/*.h")
    add_files("src/pulse_app/src/*.c")
    add_files("src/pulse_app/src/*.cpp")

target("pulse_math")
    set_kind("headeronly")
    add_includedirs("src/pulse_math/include", {public = true})
    add_headerfiles("src/pulse_math/include/*.h")

target("pulse_window")
    set_kind("static")
    add_deps("pulse_app")
    add_deps("pulse_input")
    add_packages("libsdl3", {public = true})
    add_includedirs("src/pulse_window/include", {public = true})
    add_headerfiles("src/pulse_window/include/*.h")
    add_files("src/pulse_window/src/*.cpp")

target("pulse_input")
    set_kind("static")
    add_deps("pulse_app")
    add_packages("libsdl3", {public = true})
    add_includedirs("src/pulse_input/include", {public = true})
    add_headerfiles("src/pulse_input/include/*.h")
    add_files("src/pulse_input/src/*.cpp")

target("pulse_asset")
    set_kind("static")
    add_deps("pulse_app")
    add_packages("libsdl3", {public = true})
    add_includedirs("src/pulse_asset/include", {public = true})
    add_headerfiles("src/pulse_asset/include/*.h")
    add_files("src/pulse_asset/src/*.cpp")

target("pulse_graphics")
    set_kind("static")
    set_exceptions("cxx")
    add_deps("pulse_app")
    add_deps("pulse_window")
    add_deps("pulse_asset")
    add_deps("pulse_math")
    add_deps("cgpu", {public = true})
    add_deps("ktx")
    add_defines("KHRONOS_STATIC")
    add_includedirs("src/pulse_graphics/include", {public = true})
    add_includedirs("src/pulse_graphics/rendergraph/include")
    add_headerfiles("src/pulse_graphics/include/*.h")
    add_headerfiles("src/pulse_graphics/rendergraph/include/*.h")
    add_headerfiles("src/pulse_graphics/src/*.h", {install = false})
    add_headerfiles("src/pulse_graphics/rendergraph/src/*.h", {install = false})
    add_files("src/pulse_graphics/src/*.cpp")
    add_files("src/pulse_graphics/src/**/*.cpp")
    add_files("src/pulse_graphics/rendergraph/src/*.cpp")
    add_rules("utils.hlsl2spv", {bin2c = true})
    add_files("src/pulse_graphics/src/runtime/*.hlsl")

target("pulse_renderer")
    set_kind("static")
    add_deps("pulse_app")
    add_deps("pulse_math")
    add_deps("pulse_window")
    add_deps("pulse_graphics")
    add_deps("pulse_transform")
    add_includedirs("src/pulse_renderer/include", {public = true})
    add_headerfiles("src/pulse_renderer/include/*.h")
    add_headerfiles("src/pulse_renderer/src/*.h", {install = false})
    add_files("src/pulse_renderer/src/*.cpp")

target("test-app")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_files("tests/app/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-window")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_window")
    add_files("tests/window/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-asset")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_asset")
    add_files("tests/asset/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-graphics")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_window")
    add_deps("pulse_asset")
    add_deps("pulse_graphics")
    add_files("tests/graphics/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-math")
    set_group("tests")
    set_kind("binary")
    add_deps("pulse_math")
    add_files("tests/math/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-input")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_input")
    add_files("tests/input/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("pulse_transform")
    set_kind("static")
    add_deps("pulse_app")
    add_deps("pulse_math")
    add_includedirs("src/pulse_transform/include", {public = true})
    add_headerfiles("src/pulse_transform/include/*.h")
    add_files("src/pulse_transform/src/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-transform")
    set_group("tests")
    set_kind("binary")
    add_deps("pulse_app")
    add_deps("pulse_math")
    add_deps("pulse_transform")
    add_files("tests/transform/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")

target("test-renderer")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_math")
    add_deps("pulse_graphics")
    add_deps("pulse_transform")
    add_deps("pulse_asset")
    add_deps("pulse_renderer")
    add_files("tests/renderer/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")
