add_rules("mode.debug", "mode.release", "mode.releasedbg")
set_languages("cxx20", "c11")
set_exceptions("none")
if is_plat("windows") then 
    add_defines("NOMINMAX")
    set_runtimes(is_mode("debug") and "MDd" or "MD")
    add_ldflags("-subsystem:console")
elseif is_plat("android") then
    add_cxflags("-fPIC")
    set_runtimes("c++_shared")
end

add_cxxflags("/Zc:__cplusplus", "/Zc:preprocessor", {tools = "cl", force = true})

add_cxflags("/utf-8", {tools = {"cl", "clang-cl"}, force = true})
add_cxflags("-finput-charset=utf-8", "-fexec-charset=utf-8", {tools = {"gcc", "gxx", "clang", "clangxx"}, force = true})

if is_host("windows") and is_plat("android") then
    set_policy("install.strip_packagelibs", false)
end

add_requires("libsdl3 3.4.12", {configs = {sdlmain = false, shared = true}})
add_requires("imgui v1.92.1-docking", {configs = {shared = true}})
add_requires("mimalloc")
add_requires("enkits")
add_requires("physfs")

if is_plat("windows", "linux", "android") then
    option("use_vulkan")
        set_showmenu(true )
        set_default(true)
end

includes("cgpu/xmake.lua")

includes("src/khr/xmake.lua")

includes("dascript/xmake.lua")

includes("xmake/rules/window_screenshot/xmake.lua")
includes("xmake/rules/window_title_test/xmake.lua")
includes("xmake/rules/package_output/xmake.lua")

target("pulse_platform")
    set_group("core")
    set_kind("headeronly")
    add_includedirs("src/pulse_platform/include", {public = true})
    add_headerfiles("src/pulse_platform/include/*.h")

target("pulse_app")
    set_group("core")
    set_kind("shared")
    add_defines("PULSE_APP_MODULE_BUILD")
    add_defines("flecs_EXPORTS")
    add_deps("pulse_platform")
    add_includedirs("src/pulse_app/include", {public = true})
    add_headerfiles("src/pulse_app/include/*.h")
    add_files("src/pulse_app/src/*.c")
    add_files("src/pulse_app/src/*.cpp")
    add_files("src/pulse_app/src/*.cppm", {public = true})
    add_rules("pulse.copy_package_runtime", {packages = {"libsdl3"}})

target("pulse_vfs")
    set_group("core")
    set_kind("shared")
    add_defines("PULSE_VFS_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_packages("physfs")
    add_includedirs("src/pulse_vfs/include", {public = true})
    add_headerfiles("src/pulse_vfs/include/*.h")
    add_files("src/pulse_vfs/src/*.cpp")

target("pulse_config")
    set_group("core")
    set_kind("shared")
    set_exceptions("cxx")
    add_defines("PULSE_CONFIG_MODULE_BUILD")
    add_deps("pulse_platform")
    add_includedirs("src/pulse_config/include", {public = true})
    add_headerfiles("src/pulse_config/include/*.h")
    add_files("src/pulse_config/src/*.cpp")

target("pulse_script_register")
    set_group("core")
    set_kind("headeronly")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_includedirs("src/pulse_script_register/include", {public = true})
    add_headerfiles("src/pulse_script_register/include/*.h")

target("pulse_package_loader")
    set_group("core")
    set_kind("shared")
    add_defines("PULSE_PACKAGE_LOADER_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_vfs")
    add_deps("pulse_script_register")
    add_includedirs("src/pulse_package_loader/include", {public = true})
    add_headerfiles("src/pulse_package_loader/include/*.h")
    add_files("src/pulse_package_loader/src/*.cpp")

target("pulse_math")
    set_group("pacakges")
    set_kind("headeronly")
    add_deps("pulse_platform")
    add_includedirs("src/pulse_math/include", {public = true})
    add_headerfiles("src/pulse_math/include/*.h")

target("pulse_window")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_window/package.json"})
    add_defines("PULSE_WINDOW_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_input")
    add_packages("libsdl3", {public = true})
    add_includedirs("src/pulse_window/include", {public = true})
    add_headerfiles("src/pulse_window/include/*.h")
    add_files("src/pulse_window/src/*.cpp")

target("pulse_input")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_input/package.json"})
    add_defines("PULSE_INPUT_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_packages("libsdl3", {public = true})
    add_includedirs("src/pulse_input/include", {public = true})
    add_headerfiles("src/pulse_input/include/*.h")
    add_files("src/pulse_input/src/*.cpp")

target("pulse_asset")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_asset/package.json"})
    add_defines("PULSE_ASSET_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_vfs")
    add_includedirs("src/pulse_asset/include", {public = true})
    add_headerfiles("src/pulse_asset/include/*.h")
    add_files("src/pulse_asset/src/*.cpp")

target("pulse_graphics")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_graphics/package.json"})
    add_defines("PULSE_GRAPHICS_MODULE_BUILD")
    add_deps("pulse_platform")
    set_exceptions("cxx")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_window")
    add_deps("pulse_asset")
    add_deps("pulse_math")
    add_deps("cgpu", {public = true})
    add_deps("ktx")
    add_defines("KHRONOS_STATIC")
    add_includedirs("src/pulse_graphics/include", {public = true})
    add_includedirs("src/pulse_graphics/rendergraph/include")
    add_headerfiles("src/pulse_graphics/include/*.h")
    add_headerfiles("src/pulse_graphics/rendergraph/include/*.h")
    add_headerfiles("src/pulse_graphics/src/*.h", {install = false})
    add_headerfiles("src/pulse_graphics/rendergraph/src/*.h", {install = false})
    add_files("src/pulse_graphics/src/*.cpp")
    add_files("src/pulse_graphics/src/**/*.cpp")
    add_files("src/pulse_graphics/rendergraph/src/*.cpp")
    add_rules("utils.hlsl2spv", {bin2c = true})
    add_files("src/pulse_graphics/src/runtime/*.hlsl")

target("pulse_transform")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_transform/package.json"})
    add_defines("PULSE_TRANSFORM_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_includedirs("src/pulse_transform/include", {public = true})
    add_headerfiles("src/pulse_transform/include/*.h")
    add_files("src/pulse_transform/src/*.cpp")

target("pulse_renderer")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_renderer/package.json"})
    add_defines("PULSE_RENDERER_MODULE_BUILD")
    add_deps("pulse_platform")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_deps("pulse_window")
    add_deps("pulse_graphics")
    add_deps("pulse_transform")
    add_includedirs("src/pulse_renderer/include", {public = true})
    add_headerfiles("src/pulse_renderer/include/*.h")
    add_headerfiles("src/pulse_renderer/src/*.h", {install = false})
    add_files("src/pulse_renderer/src/*.cpp")

target("pulse_imgui")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.copy_package_runtime", {packages = {"imgui"}})
    add_rules("pulse.package_install", {manifest = "src/pulse_imgui/package.json"})
    add_defines("PULSE_IMGUI_MODULE_BUILD")
    add_deps("pulse_platform")
    set_exceptions("cxx")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_window")
    add_deps("pulse_input")
    add_deps("pulse_graphics")
    add_packages("imgui", {public = true})
    add_includedirs("src/pulse_imgui/include", {public = true})
    add_headerfiles("src/pulse_imgui/include/*.h")
    add_headerfiles("src/pulse_imgui/src/*.h", {install = false})
    add_files("src/pulse_imgui/src/*.cpp")
    add_rules("utils.hlsl2spv", {bin2c = true})
    add_files("src/pulse_imgui/src/*.hlsl")

target("pulse_cpp_gameplay")
    set_group("pacakges")
    set_kind("headeronly")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_includedirs("src/pulse_cpp_gameplay/include", {public = true})
    add_headerfiles("src/pulse_cpp_gameplay/include/*.h")
    add_headerfiles("src/pulse_cpp_gameplay/include/*.hpp")

target("pulse_daslang")
    set_group("pacakges")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "src/pulse_daslang/package.json"})
    add_defines("PULSE_DASLANG_MODULE_BUILD")
    add_deps("pulse_platform")
    set_exceptions("cxx")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_deps("pulse_asset")
    add_deps("pulse_vfs")
    add_deps("pulse_graphics")
    add_deps("pulse_imgui")
    add_deps("pulse_script_register")
    add_deps("libDaScript")
    add_includedirs("src/pulse_daslang/include", {public = true})
    add_headerfiles("src/pulse_daslang/include/*.h")
    add_headerfiles("src/pulse_daslang/src/*.h", {install = false})
    add_files("src/pulse_daslang/src/*.cpp")
    if is_plat("windows") then
        add_cxflags("/bigobj")
    end

target("launcher")
    set_kind(is_plat("android") and "shared" or "binary")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_package_loader")
    add_deps("pulse_vfs")
    add_files("src/launcher/main.cpp")
    set_runargs(path.absolute("src"), path.absolute("examples"))
    add_rules("pulse.copy_manifest", {manifest = "src/launcher/launcher.manifest.json"})
    add_rules("pulse.copy_libc++shared")

for _, test_file in ipairs(os.files("tests/app/test_*.cpp")) do
    local test_name = "test-app-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/app")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "app", rundir = "$(projectdir)"})
end

for _, test_file in ipairs(os.files("tests/config/test_*.cpp")) do
    local test_name = "test-config-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/config")
        add_deps("pulse_config")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "config", rundir = "$(projectdir)"})
end

target("test-pkg-custom-entry")
    set_group("tests")
    set_kind("shared")
    set_default(false)
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_files("tests/package_loader/pkg_custom_entry/package.cpp")

target("test-pkg-assets")
    set_group("tests")
    set_kind("shared")
    set_default(false)
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_files("tests/package_loader/pkg_assets/package.cpp")

target("test-pkg-script-runtime")
    set_group("tests")
    set_kind("shared")
    set_default(false)
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_script_register")
    add_files("tests/package_loader/pkg_script_runtime/package.cpp")

for _, test_file in ipairs(os.files("tests/package_loader/test_*.cpp")) do
    local test_name = "test-package_loader-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        add_includedirs("tests/package_loader")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_deps("pulse_package_loader")
        add_deps("pulse_vfs")
        add_deps("pulse_input")
        add_deps("pulse_transform")
        if path.basename(test_file) == "test_loader_custom_entry" then
            add_deps("test-pkg-custom-entry")
        end
        if path.basename(test_file) == "test_loader_entry_and_assets" then
            add_deps("test-pkg-assets")
            add_deps("test-pkg-custom-entry")
        end
        if path.basename(test_file) == "test_loader_script_runtime" then
            add_deps("test-pkg-script-runtime")
        end
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        set_rundir("$(projectdir)")
        add_tests("default", {group = "package_loader", rundir = "$(projectdir)"})
end

target("test-window")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_window")
    add_files("tests/window/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")
    add_rules("pulse.window_title_test", { title = "test-window retitled", wait = 10, close_timeout_ms = 8000, })
    add_tests("default", {group = "window", rundir = "$(projectdir)"})

for _, test_file in ipairs(os.files("tests/asset/test_*.cpp")) do
    local test_name = "test-asset-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/asset")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_deps("pulse_asset")
        add_deps("pulse_vfs")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "asset", rundir = "$(projectdir)"})
end

for _, test_file in ipairs(os.files("tests/vfs/test_*.cpp")) do
    local test_name = "test-vfs-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_deps("pulse_vfs")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "vfs", rundir = "$(projectdir)"})
end

target("test-graphics")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_window")
    add_deps("pulse_asset")
    add_deps("pulse_vfs")
    add_deps("pulse_graphics")
    add_files("tests/graphics/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")
    add_rules("pulse.window_screenshot_test", {baseline = "tests/graphics/baseline.png", wait = 3, threshold = 0.995})
    add_tests("screenshot", {group = "graphics", rundir = "$(projectdir)"})

for _, test_file in ipairs(os.files("tests/math/test_*.cpp")) do
    local test_name = "test-math-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/math")
        add_deps("pulse_math")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "math", rundir = "$(projectdir)"})
end

for _, test_file in ipairs(os.files("tests/input/test_*.cpp")) do
    local test_name = "test-input-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/input")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_deps("pulse_input")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "input", rundir = "$(projectdir)"})
end

for _, test_file in ipairs(os.files("tests/transform/test_*.cpp")) do
    local test_name = "test-transform-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_includedirs("tests/transform")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_deps("pulse_math")
        add_deps("pulse_transform")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "transform", rundir = "$(projectdir)"})
end

target("test-renderer")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_deps("pulse_graphics")
    add_deps("pulse_transform")
    add_deps("pulse_asset")
    add_deps("pulse_vfs")
    add_deps("pulse_renderer")
    add_files("tests/renderer/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")
    add_rules("pulse.window_screenshot_test", {baseline = "tests/renderer/baseline.png", wait = 5, threshold = 0.995})
    add_tests("screenshot", {group = "renderer", rundir = "$(projectdir)"})

target("test-imgui")
    set_group("tests")
    set_kind("binary")
    set_rundir("$(projectdir)")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_window")
    add_deps("pulse_input")
    add_deps("pulse_asset")
    add_deps("pulse_vfs")
    add_deps("pulse_graphics")
    add_deps("pulse_imgui")
    add_files("tests/imgui/*.cpp")
    add_files("tests/helper/msvc_headless_asserts.c")
    add_rules("pulse.window_screenshot_test", {baseline = "tests/imgui/baseline.png", wait = 5, threshold = 0.995})
    add_tests("screenshot", {group = "imgui", rundir = "$(projectdir)"})

for _, test_file in ipairs(os.files("tests/daslang/test_*.cpp")) do
    local test_name = "test-daslang-" .. path.basename(test_file):gsub("^test_", "")
    target(test_name)
        set_group("tests")
        set_kind("binary")
        set_default(false)
        set_rundir("$(projectdir)")
        add_deps("pulse_app")
        add_deps("pulse_config")
        add_deps("pulse_math")
        add_deps("pulse_window")
        add_deps("pulse_input")
        add_deps("pulse_asset")
        add_deps("pulse_graphics")
        add_deps("pulse_imgui")
        add_deps("pulse_daslang")
        add_deps("pulse_package_loader")
        add_deps("pulse_vfs")
        add_files(test_file)
        add_files("tests/helper/msvc_headless_asserts.c")
        add_tests("default", {group = "daslang", rundir = "$(projectdir)"})
end

target("example-snake")
    set_group("examples")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "examples/snake/package.json"})
    set_basename("example_snake")
    add_defines("PULSE_SNAKE_MODULE_BUILD")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_deps("pulse_window")
    add_deps("pulse_input")
    add_deps("pulse_asset")
    add_deps("pulse_transform")
    add_deps("pulse_graphics")
    add_deps("pulse_renderer")
    add_deps("pulse_imgui")
    add_deps("pulse_cpp_gameplay")
    add_includedirs("examples/snake", {public = false, order = true})
    add_files("examples/snake/*.cpp")

