version(1)

typedef "bool"
typedef "float"
typedef "int32_t"
typedef "uint32_t"
typedef "void"
typedef "cstring"

--- From pulse_app.h
typedef "EPulseResult"
typedef "EPulseAppAddPluginResult"
typedef "PulseAppId"

--- From flecs.h
typedef "ecs_entity_t"

--- From pulse_math.h
typedef "HMM_Vec4" { cname = "HMM_Vec4" }

--- From pulse_graphics.h
typedef "PulseMeshHandle" { cname = "PulseMeshHandle" }
typedef "PulseMaterialHandle" { cname = "PulseMaterialHandle" }

--- Constants
const_value.RendererPluginDescVersion { value = "1u" }

--- ECS Components
component.Camera
    .windowEntity "ecs_entity_t"
    .fov          "float" { min = 0.001, max = 179.0 }
    .nearPlane    "float" { min = 0.001, max = 10 }
    .farPlane     "float" { min = 0.01, max = 4000 }
    .orthographicSize   "float" { min = 0.001, max = 100 }
    .orthographic "bool"
    ()

component.Light
    .color "HMM_Vec4"
    ()

component.Renderable
    .mesh     "PulseMeshHandle"
    .material "PulseMaterialHandle"
    ()

--- Functions
func.AddRendererPlugin
    "EPulseAppAddPluginResult"
    .app  "PulseAppId"
    ()
