target("example-<game>")
    set_group("examples")
    set_kind("shared")
    add_rules("pulse.package_install", {manifest = "examples/<game>/package.json"})
    set_basename("example_<game>")
    add_deps("pulse_app")
    add_deps("pulse_config")
    add_deps("pulse_math")
    add_deps("pulse_window")
    add_deps("pulse_input")
    add_deps("pulse_asset")
    add_deps("pulse_transform")
    add_deps("pulse_graphics")
    add_deps("pulse_renderer")
    add_deps("pulse_imgui")
    add_deps("pulse_cpp_gameplay")
    add_deps("pulse_prefab")
    add_deps("pulse_datatable")
    add_includedirs("examples/<game>", {public = false, order = true})
    add_includedirs("examples/<game>/schema")
    add_files("examples/<game>/*.cpp")
    add_files("examples/<game>/schema/tables_generated.cpp")
