#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_math/idl/pulse_math.idl
// ============================================================================

#include <flecs.h>

#include "pulse_math.h"

inline void pulse_math_register_reflection(ecs_world_t* world) {
    {
        flecs::component<HMM_Vec2> comp(world, "HMM_Vec2");
        comp.member("X", &HMM_Vec2::X);
        comp.member("Y", &HMM_Vec2::Y);
    }
    {
        flecs::component<HMM_Vec3> comp(world, "HMM_Vec3");
        comp.member("X", &HMM_Vec3::X);
        comp.member("Y", &HMM_Vec3::Y);
        comp.member("Z", &HMM_Vec3::Z);
    }
    {
        flecs::component<HMM_Vec4> comp(world, "HMM_Vec4");
        comp.member("X", &HMM_Vec4::X);
        comp.member("Y", &HMM_Vec4::Y);
        comp.member("Z", &HMM_Vec4::Z);
        comp.member("W", &HMM_Vec4::W);
    }
    {
        flecs::component<HMM_Quat> comp(world, "HMM_Quat");
        comp.member("X", &HMM_Quat::X);
        comp.member("Y", &HMM_Quat::Y);
        comp.member("Z", &HMM_Quat::Z);
        comp.member("W", &HMM_Quat::W);
    }
    {
        flecs::component<HMM_Mat2> comp(world, "HMM_Mat2");
        comp.member("Columns", &HMM_Mat2::Columns);
    }
    {
        flecs::component<HMM_Mat3> comp(world, "HMM_Mat3");
        comp.member("Columns", &HMM_Mat3::Columns);
    }
    {
        flecs::component<HMM_Mat4> comp(world, "HMM_Mat4");
        comp.member("Columns", &HMM_Mat4::Columns);
    }
}
