// ============================================================================
// package_register.cpp
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/gen_package_register/generate.lua
// Source: src/pulse_imgui/idl/pulse_imgui.idl
// ============================================================================
#include "pulse_config.h"
#include "pulse_imgui.h"

extern "C" {

    PULSE_IMGUI_API EPulseResult pulse_package_register(PulseAppId app, PulseConfig* config) {
    PulseImguiPluginDesc desc = pulse_imgui_plugin_desc_default();
    if (config) {
        desc.flags = (EPulseImguiPluginFlags)(uint32_t)pulse_config_get_int(config, "flags", (int64_t)desc.flags);
        desc.ini_filename = pulse_config_get_string(config, "ini_filename", desc.ini_filename);
    }
    EPulseAppAddPluginResult r = pulse_add_imgui_plugin(app, &desc);
    switch (r) {
        case PULSE_APP_ADD_PLUGIN_RESULT_OK: return PULSE_RESULT_OK;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT: return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_STATE: return PULSE_RESULT_ERROR_INVALID_STATE;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN: return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_PLUGIN_BUILD_FAILED: return PULSE_RESULT_ERROR_INTERNAL;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INTERNAL: return PULSE_RESULT_ERROR_INTERNAL;
        default: return PULSE_RESULT_ERROR_INTERNAL;
    }
}
} // extern "C"
