#include <flecs.h> // C++ API - must be included before pulse headers

#include "pulse_daslang.h"
#include "pulse_script_register.h"

#include "daslang_internal.h"

#include <filesystem>
#include <memory>
#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#else
#include <dlfcn.h>
#endif

#include "daScript/daScript.h"
#include "daScript/simulate/fs_file_info.h"

#include "das_cgpu.h"
#include "das_flecs.h"
#include "das_pulse.h"

#include "pulse_app.h"
#include "pulse_imgui.h"

ECS_COMPONENT_DECLARE(pulse_daslang_state_resource);

// NEED_MODULE/NEED_ALL_DEFAULT_MODULES must be at global scope; they emit
// references to the global register_* functions generated by REGISTER_MODULE.
void need_das_modules()
{
	NEED_ALL_DEFAULT_MODULES;
	NEED_MODULE(ModuleFlecs);
	NEED_MODULE(ModuleCGPU);
	NEED_MODULE(ModulePulse);
}

namespace pulse_daslang_internal
{
	bool s_das_environment_initialized = false;

	EPulseResult ensure_das_environment()
	{
		if (s_das_environment_initialized)
			return PULSE_RESULT_OK;

		need_das_modules();
		das::Module::Initialize();

		s_das_environment_initialized = true;
		return PULSE_RESULT_OK;
	}

	std::string module_directory()
	{
#ifdef _WIN32
		HMODULE mod = nullptr;
		if (!GetModuleHandleExA(
				GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
				reinterpret_cast<LPCSTR>(&module_directory),
				&mod))
			return {};

		char path[MAX_PATH];
		DWORD len = GetModuleFileNameA(mod, path, MAX_PATH);
		if (len == 0 || len >= MAX_PATH) return {};

		std::string full(path, len);
		auto slash = full.find_last_of("/\\");
		return slash == std::string::npos ? std::string{} : full.substr(0, slash);
#else
		Dl_info info;
		if (dladdr(reinterpret_cast<void*>(&module_directory), &info) && info.dli_fname) {
			std::string full(info.dli_fname);
			auto slash = full.find_last_of('/');
			return slash == std::string::npos ? std::string{} : full.substr(0, slash);
		}
		return {};
#endif
	}

	EPulseResult report_program_errors(const das::ProgramPtr& program, DaslangTextPrinter& printer)	
	{
		if (!program)
		{
			printer << "Daslang compilation failed: no program returned.\n";
			return PULSE_RESULT_ERROR_INTERNAL;
		}
		printer << "Daslang compilation failed:\n";
		for (auto& err : program->errors)
		{
			printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
		}
		return PULSE_RESULT_ERROR_INTERNAL;
	}

    Module::~Module()
    {
		context.reset();
		program.reset();
		module_group = das::ModuleGroup();
    }


	EPulsePluginBuildResult daslang_plugin_build(PulseAppId app, void* ctx)
	{
		auto* state = static_cast<pulse_daslang_state*>(ctx);
		if (!state)
			return PULSE_PLUGIN_BUILD_RESULT_ERROR_INVALID_ARGUMENT;

		state->app = app;
		ecs_world_t* world = pulse_app_world(app);
		if (!world)
			return PULSE_PLUGIN_BUILD_RESULT_ERROR_INVALID_ARGUMENT;

		EPulseResult env_result = ensure_das_environment();
		if (env_result != PULSE_RESULT_OK)
			return PULSE_PLUGIN_BUILD_RESULT_ERROR_INTERNAL;

        ECS_COMPONENT_DEFINE(world, pulse_daslang_state_resource);

        pulse_daslang_state_resource resource{ state };
        ecs_singleton_set_ptr(world, pulse_daslang_state_resource, &resource);

		// Event systems broadcast through the SingleHolder entity carrying
		// pulse::EventTag, mirroring the C++ module host setup.
		dasPulseECS::ensure_event_tag(world);

		state->root_path = module_directory();
		if (state->root_path.empty())
			return PULSE_PLUGIN_BUILD_RESULT_ERROR_INTERNAL;

		das::setDasRoot(state->root_path.c_str());
		return PULSE_PLUGIN_BUILD_RESULT_OK;
	}

	EPulsePluginBuildResult daslang_plugin_post_build(PulseAppId app, void* ctx)
	{
		(void)app;
		(void)ctx;
		return PULSE_PLUGIN_BUILD_RESULT_OK;
	}

	void daslang_plugin_shutdown(PulseAppId app, void* ctx)
	{
		(void)app;
		auto* state = static_cast<pulse_daslang_state*>(ctx);
		if (!state)
			return;

        state->modules.clear();

		delete state;
	}

    bool pulse_load_module(PulseAppId app, pulse_daslang_state* state, const char* c_script_path)
    {
        ecs_world_t* world = pulse_app_world(app);
        if (!world || !state) return false;

		DaslangTextPrinter printer;
		auto file_access = das::make_smart<das::FsFileAccess>();

		// 'require pulse/<module>' resolves relative to the pulse script root.
		{
			std::filesystem::path pulse_root = std::filesystem::absolute(state->root_path) / "pulse";
			file_access->addFsRoot("pulse", pulse_root.generic_string());
		}

		std::filesystem::path script_path = std::filesystem::absolute(c_script_path);

        das::ModuleGroup module_group;
		auto program = das::compileDaScript(
			script_path.generic_string().c_str(),
			file_access,
			printer,
			module_group);
		if (!program || program->failed()) {
			report_program_errors(program, printer);
            return false;
        }

		auto context = std::make_unique<das::Context>(program->getContextStackSize());
		if (!program->simulate(*context, printer))
		{
			printer << "Daslang simulation failed:\n";
			for (auto& err : program->errors)
			{
				printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
			}
			return false;
		}

		auto fn_import = context->findFunction("importModule");
		if (!fn_import)
		{
			printer << "Daslang script does not export 'importModule'.\n";
			return false;
		}

		if (!das::verifyCall<void, dasPulseECS::ModuleContext&>(fn_import->debugInfo, module_group))
		{
			printer << "Daslang 'importModule' has wrong signature; expected def importModule(var ctx: ModuleContext): void\n";
			return false;
		}

		dasPulseECS::ModuleContext module_context = {
			.world = dasPulseECS::World(world),
			.initPipeline = flecs::OnStart,
			.updatePipeline = flecs::OnUpdate,
			.postUpdatePipeline = flecs::PostUpdate,
			.renderPipeline = flecs::OnStore,
			.imguiPipeline = pulse_imgui_get_phase(app),
		};

		vec4f args[1];
		args[0] = das::cast<dasPulseECS::ModuleContext&>::from(module_context);
		context->evalWithCatch(fn_import, args);
		if (auto ex = context->getException())
		{
			printer << "exception in importModule: " << ex << " at "
					<< context->exceptionAt.describe() << "\n";
			return false;
		}

		printer << "Daslang module loaded: " << c_script_path << "\n";

        state->modules.emplace_back(c_script_path, std::move(module_group), program, std::move(context));

        return true;
    }

    pulse_daslang_state* state_from_app(PulseAppId app) {
        ecs_world_t* world = pulse_app_world(app);
        if (!world || ecs_id(pulse_daslang_state_resource) == 0) return nullptr;
        const pulse_daslang_state_resource* res = ecs_singleton_get(world, pulse_daslang_state_resource);
        return res ? res->state : nullptr;
    }

	EPulseResult daslang_script_package_load(PulseAppId app, const PulsePackageScriptInfo* info)
	{
		if (!app || !info || !info->script_file || !info->script_file[0] || !info->package_dir || !info->package_dir[0])
			return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

		std::filesystem::path script = std::filesystem::absolute(
			std::filesystem::path(info->package_dir) / info->script_file);

		if (!::pulse_load_module(app, script.generic_string().c_str()))
			return PULSE_RESULT_ERROR_INTERNAL;
		return PULSE_RESULT_OK;
	}
}

extern "C" {

PulseDaslangPluginDesc pulse_daslang_plugin_desc_default(void)
{
	PulseDaslangPluginDesc desc = {
		sizeof(PulseDaslangPluginDesc),
		PULSE_DASLANG_PLUGIN_DESC_VERSION,
	};
	return desc;
}

EPulseAppAddPluginResult pulse_add_daslang_plugin(PulseAppId app, const PulseDaslangPluginDesc* desc)
{
	if (!app || !desc)
		return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT;
	if (desc->struct_size != sizeof(PulseDaslangPluginDesc) || desc->version != PULSE_DASLANG_PLUGIN_DESC_VERSION)
		return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT;

	if (pulse_app_has_plugin(app, pulse_daslang_internal::kPluginName))
		return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN;

	auto* state = new pulse_daslang_internal::pulse_daslang_state();

	PulsePluginDesc plugin_desc = {
		.struct_size = sizeof(PulsePluginDesc),
		.version = PULSE_PLUGIN_DESC_VERSION,
		.plugin_version = PULSE_DASLANG_PLUGIN_DESC_VERSION,
		.name = pulse_daslang_internal::kPluginName,
		.ctx = state,
		.build = pulse_daslang_internal::daslang_plugin_build,
		.post_build = pulse_daslang_internal::daslang_plugin_post_build,
		.shutdown = pulse_daslang_internal::daslang_plugin_shutdown,
		.dependency_count = 0,
		.dependencies = nullptr,
	};

	EPulseAppAddPluginResult result = pulse_app_add_plugin(app, &plugin_desc);
	if (result != PULSE_APP_ADD_PLUGIN_RESULT_OK && !pulse_app_has_plugin(app, pulse_daslang_internal::kPluginName))
		delete state;
	return result;
}

bool pulse_load_module(PulseAppId app, const char* script_path)
{
    auto state = pulse_daslang_internal::state_from_app(app);
    return pulse_daslang_internal::pulse_load_module(app, state, script_path);
}

PULSE_DASLANG_API uint32_t pulse_package_get_runtimes(const PulseScriptRuntimeDesc** out_runtimes)
{
	static const PulseScriptRuntimeDesc runtimes[] = {
		{ "daslang", pulse_daslang_internal::daslang_script_package_load },
	};
	if (!out_runtimes)
		return 0;
	*out_runtimes = runtimes;
	return 1;
}

} // extern "C"
