#include <flecs.h> // C++ API - must be included before pulse headers

#include "pulse_daslang.h"

#include <filesystem>
#include <memory>
#include <stdio.h>
#include <string.h>

#include "daScript/daScript.h"
#include "daScript/simulate/fs_file_info.h"

#include "das_cgpu.h"
#include "das_flecs.h"
#include "das_pulse.h"

#include "pulse_app.h"
#include "pulse_imgui.h"

// NEED_MODULE/NEED_ALL_DEFAULT_MODULES must be at global scope; they emit
// references to the global register_* functions generated by REGISTER_MODULE.
void need_das_modules()
{
	NEED_ALL_DEFAULT_MODULES;
	NEED_MODULE(ModuleFlecs);
	NEED_MODULE(ModuleCGPU);
	NEED_MODULE(ModulePulse);
}

namespace pulse_daslang_internal
{
	constexpr const char* kPluginName = "PulseDaslangPlugin";

	struct PluginState
	{
		PulseAppId app = nullptr;
		std::string root_path;
		std::string script_path;
		das::ModuleGroup module_group;
		das::ProgramPtr program;
		std::unique_ptr<das::Context> context;
	};

	class DaslangTextPrinter : public das::TextWriter
	{
	public:
		virtual void output() override
		{
			uint64_t new_pos = tellp();
			if (new_pos != pos)
			{
				fwrite(data() + pos, 1, static_cast<size_t>(new_pos - pos), stdout);
				fflush(stdout);
				pos = new_pos;
			}
		}

	protected:
		uint64_t pos = 0;
	};

	bool s_das_environment_initialized = false;

	EPulseResult ensure_das_environment()
	{
		if (s_das_environment_initialized)
			return PULSE_RESULT_OK;

		need_das_modules();
		das::Module::Initialize();

		s_das_environment_initialized = true;
		return PULSE_RESULT_OK;
	}

	EPulseResult report_program_errors(const das::ProgramPtr& program, DaslangTextPrinter& printer)
	{
		printer << "Daslang compilation failed:\n";
		for (auto& err : program->errors)
		{
			printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
		}
		return PULSE_RESULT_ERROR_INTERNAL;
	}

	EPulseResult daslang_plugin_build(PulseAppId app, void* ctx)
	{
		auto* state = static_cast<PluginState*>(ctx);
		if (!state)
			return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

		state->app = app;
		ecs_world_t* world = pulse_app_world(app);
		if (!world)
			return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

		EPulseResult env_result = ensure_das_environment();
		if (env_result != PULSE_RESULT_OK)
			return env_result;

		// Event systems broadcast through the SingleHolder entity carrying
		// pulse::EventTag, mirroring the C++ module host setup.
		dasPulseECS::ensure_event_tag(world);

		das::setDasRoot(state->root_path.c_str());

		DaslangTextPrinter printer;
		auto file_access = das::make_smart<das::FsFileAccess>();

		// 'require pulse/<module>' resolves relative to the pulse script root.
		{
			std::filesystem::path pulse_root = std::filesystem::absolute(state->root_path) / "pulse";
			file_access->addFsRoot("pulse", pulse_root.generic_string());
		}

		std::filesystem::path script_path = std::filesystem::absolute(state->script_path);

		state->program = das::compileDaScript(
			script_path.generic_string().c_str(),
			file_access,
			printer,
			state->module_group);
		if (!state->program || state->program->failed())
			return report_program_errors(state->program, printer);

		state->context = std::make_unique<das::Context>(state->program->getContextStackSize());
		if (!state->program->simulate(*state->context, printer))
		{
			printer << "Daslang simulation failed:\n";
			for (auto& err : state->program->errors)
			{
				printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
			}
			return PULSE_RESULT_ERROR_INTERNAL;
		}

		auto fn_import = state->context->findFunction("importModule");
		if (!fn_import)
		{
			printer << "Daslang script does not export 'importModule'.\n";
			return PULSE_RESULT_ERROR_INTERNAL;
		}

		if (!das::verifyCall<void, dasPulseECS::ModuleContext&>(fn_import->debugInfo, state->module_group))
		{
			printer << "Daslang 'importModule' has wrong signature; expected def importModule(var ctx: ModuleContext): void\n";
			return PULSE_RESULT_ERROR_INTERNAL;
		}

		dasPulseECS::ModuleContext module_context = {
			.world = dasPulseECS::World(world),
			.initPipeline = flecs::OnStart,
			.updatePipeline = flecs::OnUpdate,
			.postUpdatePipeline = flecs::PostUpdate,
			.renderPipeline = flecs::OnStore,
			.imguiPipeline = pulse_imgui_get_phase(app),
		};

		vec4f args[1];
		args[0] = das::cast<dasPulseECS::ModuleContext&>::from(module_context);
		state->context->evalWithCatch(fn_import, args);
		if (auto ex = state->context->getException())
		{
			printer << "exception in importModule: " << ex << " at "
					<< state->context->exceptionAt.describe() << "\n";
			return PULSE_RESULT_ERROR_INTERNAL;
		}

		printer << "Daslang module loaded: " << state->script_path << "\n";
		return PULSE_RESULT_OK;
	}

	EPulseResult daslang_plugin_post_build(PulseAppId app, void* ctx)
	{
		(void)app;
		(void)ctx;
		return PULSE_RESULT_OK;
	}

	void daslang_plugin_shutdown(PulseAppId app, void* ctx)
	{
		(void)app;
		auto* state = static_cast<PluginState*>(ctx);
		if (!state)
			return;

		state->context.reset();
		state->program.reset();
		state->module_group = das::ModuleGroup();

		delete state;
	}
}

using namespace pulse_daslang_internal;

extern "C" {

PulseDaslangPluginDesc pulse_daslang_plugin_desc_default(void)
{
	PulseDaslangPluginDesc desc = {
		sizeof(PulseDaslangPluginDesc),
		PULSE_DASLANG_PLUGIN_DESC_VERSION,
		nullptr,
		nullptr,
	};
	return desc;
}

EPulseResult pulse_add_daslang_plugin(PulseAppId app, const PulseDaslangPluginDesc* desc)
{
	if (!app || !desc)
		return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
	if (desc->struct_size != sizeof(PulseDaslangPluginDesc) || desc->version != PULSE_DASLANG_PLUGIN_DESC_VERSION)
		return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
	if (!desc->root_path || !desc->script_path)
		return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

	if (pulse_app_has_plugin(app, kPluginName))
		return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;

	auto* state = new PluginState();
	state->root_path = desc->root_path;
	state->script_path = desc->script_path;

	PulsePluginDesc plugin_desc = {
		sizeof(PulsePluginDesc),
		PULSE_PLUGIN_DESC_VERSION,
		kPluginName,
		state,
		daslang_plugin_build,
		daslang_plugin_post_build,
		daslang_plugin_shutdown,
	};

	EPulseResult result = pulse_app_add_plugin(app, &plugin_desc);
	if (result != PULSE_RESULT_OK && !pulse_app_has_plugin(app, kPluginName))
		delete state;
	return result;
}

} // extern "C"
