#include <flecs.h> // C++ API - must be included before pulse headers

#include "pulse_daslang.h"
#include "pulse_script_register.h"

#include "daslang_internal.h"

#include <vector>
#include <memory>
#include <stdio.h>

#include "daScript/daScript.h"
#include "daScript/simulate/fs_file_info.h"

#include "das_flecs.h"

#include "pulse_app.h"
#include "pulse_imgui.h"

ECS_COMPONENT_DECLARE(pulse_daslang_state_resource);

// NEED_MODULE/NEED_ALL_DEFAULT_MODULES must be at global scope; they emit
// references to the global register_* functions generated by REGISTER_MODULE.
void need_das_modules()
{
    NEED_ALL_DEFAULT_MODULES;
    NEED_MODULE(ModuleFlecs);
    NEED_MODULE(ModuleCGPU);
    NEED_MODULE(ModulePulse);
}

namespace pulse_daslang_internal
{
    bool s_das_environment_initialized = false;

    pulse_daslang_state* state_from_app(PulseAppId app) {
        ecs_world_t* world = pulse_app_world(app);
        if (!world || ecs_id(pulse_daslang_state_resource) == 0) return nullptr;
        const pulse_daslang_state_resource* res = ecs_singleton_get(world, pulse_daslang_state_resource);
        return res ? res->state : nullptr;
    }

    EPulseResult ensure_das_environment()
    {
        if (s_das_environment_initialized)
            return PULSE_RESULT_OK;

        need_das_modules();
        das::Module::Initialize();

        s_das_environment_initialized = true;
        return PULSE_RESULT_OK;
    }

    EPulseResult report_program_errors(const das::ProgramPtr& program, DaslangTextPrinter& printer)
    {
        if (!program)
        {
            printer << "Daslang compilation failed: no program returned.\n";
            return PULSE_RESULT_ERROR_INTERNAL;
        }
        printer << "Daslang compilation failed:\n";
        for (auto& err : program->errors)
        {
            printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
        }
        return PULSE_RESULT_ERROR_INTERNAL;
    }

    Module::~Module()
    {
        context.reset();
        program.reset();
        module_group = das::ModuleGroup();
    }

    std::string normalize_cache_key(std::string_view path)
    {
        std::string_view p = path;
        while (!p.empty() && (p.front() == '/' || p.front() == '\\'))
            p.remove_prefix(1);
        while (p.size() >= 2 && p[0] == '.' && p[1] == '/')
            p.remove_prefix(2);
        return std::string(p);
    }

    class DasCacheFileAccess : public das::FsFileAccess
    {
    public:
        explicit DasCacheFileAccess(pulse_daslang_state* state)
            : state_(state)
        {
        }

        das::FileInfo* getNewFileInfo(const das::string& fileName) override
        {
            if (locked) return nullptr;
            if (!state_ || fileName.empty())
                return nullptr;

            const std::string* text = lookup_script(fileName);
            if (!text)
            {
                fprintf(stderr, "daslang: script '%s' not in injected cache (compile-time miss)\n", fileName.c_str());
                return nullptr;
            }

            if (text->size() > static_cast<size_t>(UINT32_MAX))
                return nullptr;

            das::FileInfoPtr info = das::make_unique<das::TextFileInfo>(text->data(), static_cast<uint32_t>(text->size()), false);
            return setFileInfo(fileName, das::move(info));
        }

    private:
        const std::string* lookup_script(const std::string& name) const
        {
            auto find = [&](const std::string& key) -> const std::string* {
                auto it = state_->script_cache.find(key);
                return it == state_->script_cache.end() ? nullptr : &it->second;
            };

            if (const std::string* hit = find(name)) return hit;

            std::string bare = normalize_cache_key(name);
            if (bare != name) {
                if (const std::string* hit = find(bare)) return hit;
            }

            std::string with_ext = bare;
            if (with_ext.size() < 4 || with_ext.compare(with_ext.size() - 4, 4, ".das") != 0)
                with_ext += ".das";
            if (with_ext != bare) {
                if (const std::string* hit = find(with_ext)) return hit;
            }

            if (!state_->das_root.empty())
            {
                std::string rooted = state_->das_root + "/" + bare;
                if (rooted != bare) {
                    if (const std::string* hit = find(rooted)) return hit;
                }
                if (!with_ext.empty() && with_ext != rooted)
                {
                    std::string rooted_ext = state_->das_root + "/" + with_ext;
                    if (rooted_ext != with_ext) {
                        if (const std::string* hit = find(rooted_ext)) return hit;
                    }
                }
            }
            return nullptr;
        }

        pulse_daslang_state* state_;
    };

    bool compile_script_into(pulse_daslang_state* state, const std::string& script_key, Module& out_module)
    {
        DaslangTextPrinter printer;
        if (!state->access)
            return false;

        auto it = state->script_cache.find(script_key);
        if (it == state->script_cache.end())
            return false;
        const std::string& text = it->second;
        if (text.size() > static_cast<size_t>(UINT32_MAX))
        {
            printer << "Daslang script too large: " << script_key << "\n";
            return false;
        }
        das::FileInfoPtr file_info = das::make_unique<das::TextFileInfo>(text.data(), static_cast<uint32_t>(text.size()), false);
        state->access->setFileInfo(script_key, std::move(file_info));

        das::ModuleGroup module_group;
        auto program = das::compileDaScript(script_key, state->access, printer, module_group);
        if (!program || program->failed()) {
            report_program_errors(program, printer);
            return false;
        }

        auto context = std::make_unique<das::Context>(program->getContextStackSize());
        if (!program->simulate(*context, printer))
        {
            printer << "Daslang simulation failed:\n";
            for (auto& err : program->errors)
            {
                printer << das::reportError(err.at, err.what, err.extra, err.fixme, err.cerr);
            }
            return false;
        }

        das::FileInfoPtr main_file_info = state->access->letGoOfFileInfo(script_key);
        out_module = Module(script_key, std::move(main_file_info), std::move(module_group), program, std::move(context));
        return true;
    }

    bool run_module_import(PulseAppId app, pulse_daslang_state* state, Module& module)
    {
        if (!app || !state || !module.context)
            return false;

        ecs_world_t* world = pulse_app_world(app);
        if (!world)
            return false;

        DaslangTextPrinter printer;

        auto fn_import = module.context->findFunction("importModule");
        if (!fn_import)
        {
            printer << "Daslang script does not export 'importModule'.\n";
            return false;
        }

        if (!das::verifyCall<void, dasPulseECS::ModuleContext&>(fn_import->debugInfo, module.module_group))
        {
            printer << "Daslang 'importModule' has wrong signature; expected def importModule(var ctx: ModuleContext): void\n";
            return false;
        }

        dasPulseECS::ModuleContext module_context = {
            .world = dasPulseECS::World(world),
            .initPipeline = flecs::OnStart,
            .updatePipeline = flecs::OnUpdate,
            .postUpdatePipeline = flecs::PostUpdate,
            .renderPipeline = flecs::OnStore,
            .imguiPipeline = pulse_imgui_get_phase(app),
        };

        vec4f args[1];
        args[0] = das::cast<dasPulseECS::ModuleContext&>::from(module_context);
        module.context->evalWithCatch(fn_import, args);
        if (auto ex = module.context->getException())
        {
            printer << "exception in importModule: " << ex << " at "
                    << module.context->exceptionAt.describe() << "\n";
            return false;
        }

        printer << "Daslang module loaded: " << module.script_path << "\n";
        return true;
    }

    bool compile_entry_from_cache(pulse_daslang_state* state, const std::string& key)
    {
        if (!state || !state->app || key.empty())
            return false;

        Module module;
        if (!compile_script_into(state, key, module))
            return false;
        if (!run_module_import(state->app, state, module))
            return false;
        state->modules.push_back(std::move(module));
        return true;
    }

    EPulseResult daslang_script_load(PulseAppId app, const char* path, const char* text, uint64_t text_size)
    {
        if (!app || !path || !path[0] || (!text && text_size > 0))
            return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

        auto* state = state_from_app(app);
        if (!state)
            return PULSE_RESULT_ERROR_INTERNAL;
        if (state->post_build_done)
        {
            fprintf(stderr, "daslang: script injection rejected after PostBuild: %s\n", path);
            return PULSE_RESULT_ERROR_INVALID_STATE;
        }

        std::string key = normalize_cache_key(path);
        if (key.empty())
            return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        state->script_cache[key].assign(text ? text : "", static_cast<size_t>(text_size));
        return PULSE_RESULT_OK;
    }

    EPulseResult daslang_script_package_load(PulseAppId app, const char* script_file)
    {
        if (!app || !script_file || !script_file[0])
            return PULSE_RESULT_ERROR_INVALID_ARGUMENT;

        auto* state = state_from_app(app);
        if (!state)
            return PULSE_RESULT_ERROR_INTERNAL;
        if (state->post_build_done)
        {
            fprintf(stderr, "daslang: entry registration rejected after PostBuild: %s\n", script_file);
            return PULSE_RESULT_ERROR_INVALID_STATE;
        }

        std::string key = normalize_cache_key(script_file);
        if (key.empty())
            return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        if (state->script_cache.find(key) == state->script_cache.end())
        {
            fprintf(stderr, "daslang: entry '%s' not injected before package load, cannot queue for compile\n", key.c_str());
            return PULSE_RESULT_ERROR_INTERNAL;
        }
        for (const auto& pending : state->pending_scripts)
        {
            if (pending == key)
                return PULSE_RESULT_OK;
        }
        state->pending_scripts.push_back(std::move(key));
        return PULSE_RESULT_OK;
    }

    void process_pending_scripts(pulse_daslang_state* state)
    {
        if (!state || !state->app)
            return;

        for (auto it = state->pending_scripts.begin(); it != state->pending_scripts.end(); )
        {
            if (compile_entry_from_cache(state, *it))
                it = state->pending_scripts.erase(it);
            else
            {
                fprintf(stderr, "daslang: entry '%s' failed to compile, dropping it\n", it->c_str());
                it = state->pending_scripts.erase(it);
            }
        }
    }

    static void process_pending_scripts_callback(ecs_iter_t* it)
    {
        auto* state = static_cast<pulse_daslang_state*>(it->ctx);
        if (state)
            process_pending_scripts(state);
    }

    void install_script_process_system(ecs_world_t* world, pulse_daslang_state* state)
    {
        if (!world || !state)
            return;

        ecs_entity_desc_t entity_desc{};
        entity_desc.name = "PulseDaslangProcessScripts";

        ecs_system_desc_t system_desc{};
        system_desc.entity = ecs_entity_init(world, &entity_desc);
        system_desc.phase = EcsOnLoad;
        system_desc.callback = process_pending_scripts_callback;
        system_desc.ctx = state;
        state->process_system = ecs_system_init(world, &system_desc);
    }

    EPulsePluginBuildResult daslang_plugin_build(PulseAppId app, void* ctx)
    {
        auto* state = static_cast<pulse_daslang_state*>(ctx);
        if (!state)
            return PULSE_PLUGIN_BUILD_RESULT_ERROR_INVALID_ARGUMENT;

        state->app = app;

        ecs_world_t* world = pulse_app_world(app);
        if (!world)
            return PULSE_PLUGIN_BUILD_RESULT_ERROR_INVALID_ARGUMENT;

        EPulseResult env_result = ensure_das_environment();
        if (env_result != PULSE_RESULT_OK)
            return PULSE_PLUGIN_BUILD_RESULT_ERROR_INTERNAL;

        ecs_id(pulse_daslang_state_resource) = flecs::_::type<pulse_daslang_state_resource>::id(world);

        pulse_daslang_state_resource resource{ state };
        ecs_singleton_set_ptr(world, pulse_daslang_state_resource, &resource);

        dasPulseECS::ensure_event_tag(world);

        state->das_root = "das";
        das::setDasRoot(state->das_root.c_str());

        state->access = das::make_smart<DasCacheFileAccess>(state);
        state->access->addFsRoot("pulse", state->das_root + "/pulse");
        install_script_process_system(world, state);

        return PULSE_PLUGIN_BUILD_RESULT_OK;
    }

    EPulsePluginBuildResult daslang_plugin_post_build(PulseAppId app, void* ctx)
    {
        (void)app;
        auto* state = static_cast<pulse_daslang_state*>(ctx);
        if (!state)
            return PULSE_PLUGIN_BUILD_RESULT_ERROR_INVALID_ARGUMENT;

        process_pending_scripts(state);
        state->post_build_done = true;
        return PULSE_PLUGIN_BUILD_RESULT_OK;
    }

    void daslang_plugin_shutdown(PulseAppId app, void* ctx)
    {
        (void)app;
        auto* state = static_cast<pulse_daslang_state*>(ctx);
        if (!state)
            return;

        state->pending_scripts.clear();
        state->modules.clear();
        state->script_cache.clear();

        delete state;
    }

} // namespace

extern "C" {

PulseDaslangPluginDesc pulse_daslang_plugin_desc_default(void)
{
    PulseDaslangPluginDesc desc = {
        sizeof(PulseDaslangPluginDesc),
        PULSE_DASLANG_PLUGIN_DESC_VERSION,
    };
    return desc;
}

EPulseAppAddPluginResult pulse_add_daslang_plugin(PulseAppId app, const PulseDaslangPluginDesc* desc)
{
    if (!app || !desc)
        return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT;
    if (desc->struct_size != sizeof(PulseDaslangPluginDesc) || desc->version != PULSE_DASLANG_PLUGIN_DESC_VERSION)
        return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT;

    if (pulse_app_has_plugin(app, pulse_daslang_internal::kPluginName))
        return PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN;

    auto* state = new pulse_daslang_internal::pulse_daslang_state();

    PulsePluginDesc plugin_desc = {
        .struct_size = sizeof(PulsePluginDesc),
        .version = PULSE_PLUGIN_DESC_VERSION,
        .plugin_version = PULSE_DASLANG_PLUGIN_DESC_VERSION,
        .name = pulse_daslang_internal::kPluginName,
        .ctx = state,
        .build = pulse_daslang_internal::daslang_plugin_build,
        .post_build = pulse_daslang_internal::daslang_plugin_post_build,
        .shutdown = pulse_daslang_internal::daslang_plugin_shutdown,
        .dependency_count = 0,
        .dependencies = nullptr,
    };

    EPulseAppAddPluginResult result = pulse_app_add_plugin(app, &plugin_desc);
    if (result != PULSE_APP_ADD_PLUGIN_RESULT_OK && !pulse_app_has_plugin(app, pulse_daslang_internal::kPluginName))
        delete state;
    return result;
}

bool pulse_load_module(PulseAppId app, const char* script_path)
{
    auto state = pulse_daslang_internal::state_from_app(app);
    if (!state)
        return false;
    if (!script_path || !script_path[0])
        return false;

    std::string key = pulse_daslang_internal::normalize_cache_key(script_path);
    if (key.empty())
        return false;

    if (state->script_cache.find(key) == state->script_cache.end())
    {
        fprintf(stderr, "daslang: script '%s' not injected before PostBuild, cannot queue for compile\n", key.c_str());
        return false;
    }
    for (const auto& pending : state->pending_scripts)
    {
        if (pending == key)
            return true;
    }
    state->pending_scripts.push_back(std::move(key));
    return true;
}

PULSE_DASLANG_API uint32_t pulse_package_get_runtimes(const PulseScriptRuntimeDesc** out_runtimes)
{
    static const PulseScriptRuntimeDesc runtimes[] = {
        { "daslang", "das", pulse_daslang_internal::daslang_script_load, pulse_daslang_internal::daslang_script_package_load },
    };
    if (!out_runtimes)
        return 0;
    *out_runtimes = runtimes;
    return 1;
}

} // extern "C"
