#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_text_render/idl/pulse_text_render.idl
// ============================================================================

#include <flecs.h>

#include "pulse_text_render.h"

inline void pulse_text_render_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseText> comp(world, "PulseText");
        ecs_id(PulseText) = comp.id();
        comp.member("block", &PulseText::block);
        comp.member("text", &PulseText::text);
        comp.member("box_width", &PulseText::box_width);
        comp.member("box_height", &PulseText::box_height);
    }
}
