.\lua54.exe generate-binding.lua ..\..\src\pulse_app\idl\pulse_app.idl ..\..\src\pulse_app\idl\temp.pulse_app.h c ..\..\src\pulse_app\include\pulse_app.h Pulse "    "
.\lua54.exe generate-binding.lua ..\..\src\pulse_window\idl\pulse_window.idl ..\..\src\pulse_window\idl\temp.pulse_window.h c ..\..\src\pulse_window\include\pulse_window.h Pulse "    "
.\lua54.exe generate-binding.lua ..\..\src\pulse_input\idl\pulse_input.idl ..\..\src\pulse_input\idl\temp.pulse_input.h c ..\..\src\pulse_input\include\pulse_input.h Pulse "    "
.\lua54.exe generate-binding.lua ..\..\src\pulse_asset\idl\pulse_asset.idl ..\..\src\pulse_asset\idl\temp.pulse_asset.h c ..\..\src\pulse_asset\include\pulse_asset.h Pulse "    "
.\lua54.exe generate-binding.lua ..\..\src\pulse_graphics\idl\pulse_graphics.idl ..\..\src\pulse_graphics\idl\temp.pulse_graphics.h c ..\..\src\pulse_graphics\include\pulse_graphics.h Pulse "    "
.\lua54.exe generate-binding.lua ..\..\src\pulse_transform\idl\pulse_transform.idl ..\..\src\pulse_transform\idl\temp.pulse_transform.h c ..\..\src\pulse_transform\include\pulse_transform.h Pulse "    "
