#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: $source
// ============================================================================

#include <flecs.h>

#include "$header"

inline void $function_name(ecs_world_t* world) {
$reflection
}
