// ============================================================================
// package_register.cpp
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/gen_package_register/generate.lua
// Source: src/pulse_graphics/idl/pulse_graphics.idl
// ============================================================================
#include "pulse_config.h"
#include "pulse_graphics.h"

extern "C" {

    PULSE_GRAPHICS_API EPulseResult pulse_package_register(PulseAppId app, PulseConfig* config) {
    PulseGraphicsPluginDesc desc = pulse_graphics_plugin_desc_default();
    if (config) {
        desc.image_count = (uint32_t)pulse_config_get_int(config, "image_count", desc.image_count);
        desc.enable_debug_layer = pulse_config_get_bool(config, "enable_debug_layer", desc.enable_debug_layer);
        desc.enable_gpu_based_validation = pulse_config_get_bool(config, "enable_gpu_based_validation", desc.enable_gpu_based_validation);
        desc.enable_vsync = pulse_config_get_bool(config, "enable_vsync", desc.enable_vsync);
        desc.per_draw_shader_property_count = (uint32_t)pulse_config_get_int(config, "per_draw_shader_property_count", desc.per_draw_shader_property_count);
    }
    EPulseAppAddPluginResult r = pulse_add_graphics_plugin(app, &desc);
    switch (r) {
        case PULSE_APP_ADD_PLUGIN_RESULT_OK: return PULSE_RESULT_OK;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT: return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_STATE: return PULSE_RESULT_ERROR_INVALID_STATE;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN: return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_PLUGIN_BUILD_FAILED: return PULSE_RESULT_ERROR_INTERNAL;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INTERNAL: return PULSE_RESULT_ERROR_INTERNAL;
        default: return PULSE_RESULT_ERROR_INTERNAL;
    }
}
} // extern "C"
