// ============================================================================
// package_register.cpp
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/gen_package_register/generate.lua
// Source: src/pulse_window/idl/pulse_window.idl
// ============================================================================
#include "pulse_config.h"
#include "pulse_window.h"

extern "C" {

    PULSE_WINDOW_API EPulseResult pulse_package_register(PulseAppId app, PulseConfig* config) {
    PulseWindowPluginDesc desc = pulse_window_plugin_desc_default();
    if (config) {
        PulseConfig* config_primary_window = pulse_config_get_obj(config, "primary_window");
        if (config_primary_window) {
            desc.primary_window.title = pulse_config_get_string(config_primary_window, "title", desc.primary_window.title);
            desc.primary_window.width = (int32_t)pulse_config_get_int(config_primary_window, "width", desc.primary_window.width);
            desc.primary_window.height = (int32_t)pulse_config_get_int(config_primary_window, "height", desc.primary_window.height);
            desc.primary_window.resizable = pulse_config_get_bool(config_primary_window, "resizable", desc.primary_window.resizable);
            desc.primary_window.external_graphics_context = pulse_config_get_bool(config_primary_window, "external_graphics_context", desc.primary_window.external_graphics_context);
        }
        desc.flags = (EPulseWindowPluginFlags)(uint32_t)pulse_config_get_int(config, "flags", (int64_t)desc.flags);
        desc.sdl_init_flags = (uint32_t)pulse_config_get_int(config, "sdl_init_flags", desc.sdl_init_flags);
    }
    EPulseAppAddPluginResult r = pulse_add_window_plugin(app, &desc);
    switch (r) {
        case PULSE_APP_ADD_PLUGIN_RESULT_OK: return PULSE_RESULT_OK;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT: return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_STATE: return PULSE_RESULT_ERROR_INVALID_STATE;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN: return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_PLUGIN_BUILD_FAILED: return PULSE_RESULT_ERROR_INTERNAL;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INTERNAL: return PULSE_RESULT_ERROR_INTERNAL;
        default: return PULSE_RESULT_ERROR_INTERNAL;
    }
}
} // extern "C"
