#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_window/idl/pulse_window.idl
// ============================================================================

#include <flecs.h>

#include "pulse_window.h"

inline void pulse_window_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseWindow> comp(world, "PulseWindow");
        ecs_id(PulseWindow) = comp.id();
        comp.member("width", &PulseWindow::width);
        comp.member("height", &PulseWindow::height);
        comp.member("resizable", &PulseWindow::resizable);
        comp.member("external_graphics_context", &PulseWindow::external_graphics_context);
    }
    {
        flecs::component<PulseSdlWindow> comp(world, "PulseSdlWindow");
        ecs_id(PulseSdlWindow) = comp.id();
        comp.member("window_id", &PulseSdlWindow::window_id);
    }
    {
        flecs::component<PulseTextInputEvent> comp(world, "PulseTextInputEvent");
        ecs_id(PulseTextInputEvent) = comp.id();
        comp.member("text", &PulseTextInputEvent::text);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseTextInputEvent, window));
    }
    {
        flecs::component<PulseWindowFocusEvent> comp(world, "PulseWindowFocusEvent");
        ecs_id(PulseWindowFocusEvent) = comp.id();
        comp.member("focused", &PulseWindowFocusEvent::focused);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseWindowFocusEvent, window));
    }
    {
        flecs::component<PulseWindowMouseHoverEvent> comp(world, "PulseWindowMouseHoverEvent");
        ecs_id(PulseWindowMouseHoverEvent) = comp.id();
        comp.member("entered", &PulseWindowMouseHoverEvent::entered);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseWindowMouseHoverEvent, window));
    }
    {
        flecs::component<PulsePrimaryWindow> comp(world, "PulsePrimaryWindow");
        ecs_id(PulsePrimaryWindowId) = PulsePrimaryWindowId = comp.id();
    }
    {
        flecs::component<PulseWindowCloseRequested> comp(world, "PulseWindowCloseRequested");
        ecs_id(PulseWindowCloseRequestedId) = PulseWindowCloseRequestedId = comp.id();
    }
    {
        flecs::component<PulseWindowResized> comp(world, "PulseWindowResized");
        ecs_id(PulseWindowResizedId) = PulseWindowResizedId = comp.id();
    }
}
