#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_input/idl/pulse_input.idl
// ============================================================================

#include <flecs.h>

#include "pulse_input.h"

inline void pulse_input_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseKeyboardInput> comp(world, "PulseKeyboardInput");
        ecs_id(PulseKeyboardInput) = comp.id();
        comp.member("pressed", &PulseKeyboardInput::pressed);
        comp.member("just_pressed", &PulseKeyboardInput::just_pressed);
        comp.member("just_released", &PulseKeyboardInput::just_released);
    }
    {
        flecs::component<PulseMouseInput> comp(world, "PulseMouseInput");
        ecs_id(PulseMouseInput) = comp.id();
        comp.member("state", &PulseMouseInput::state);
        comp.member("just_pressed", &PulseMouseInput::just_pressed);
        comp.member("just_released", &PulseMouseInput::just_released);
    }
    {
        flecs::component<PulseMouseMotion> comp(world, "PulseMouseMotion");
        ecs_id(PulseMouseMotion) = comp.id();
        comp.member("delta_x", &PulseMouseMotion::delta_x);
        comp.member("delta_y", &PulseMouseMotion::delta_y);
        comp.member("x", &PulseMouseMotion::x);
        comp.member("y", &PulseMouseMotion::y);
    }
    {
        flecs::component<PulseMouseScroll> comp(world, "PulseMouseScroll");
        ecs_id(PulseMouseScroll) = comp.id();
        comp.member("x", &PulseMouseScroll::x);
        comp.member("y", &PulseMouseScroll::y);
    }
    {
        flecs::component<PulseKeyEvent> comp(world, "PulseKeyEvent");
        ecs_id(PulseKeyEvent) = comp.id();
        comp.member("scancode", &PulseKeyEvent::scancode);
        comp.member("keycode", &PulseKeyEvent::keycode);
        comp.member("mod", &PulseKeyEvent::mod);
        comp.member("pressed", &PulseKeyEvent::pressed);
        comp.member("repeat", &PulseKeyEvent::repeat);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseKeyEvent, window));
    }
    {
        flecs::component<PulseMouseButtonEvent> comp(world, "PulseMouseButtonEvent");
        ecs_id(PulseMouseButtonEvent) = comp.id();
        comp.member("button", &PulseMouseButtonEvent::button);
        comp.member("pressed", &PulseMouseButtonEvent::pressed);
        comp.member("x", &PulseMouseButtonEvent::x);
        comp.member("y", &PulseMouseButtonEvent::y);
        comp.member("is_touch", &PulseMouseButtonEvent::is_touch);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseMouseButtonEvent, window));
    }
    {
        flecs::component<PulseMouseScrollEvent> comp(world, "PulseMouseScrollEvent");
        ecs_id(PulseMouseScrollEvent) = comp.id();
        comp.member("x", &PulseMouseScrollEvent::x);
        comp.member("y", &PulseMouseScrollEvent::y);
        comp.member("is_touch", &PulseMouseScrollEvent::is_touch);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseMouseScrollEvent, window));
    }
    {
        flecs::component<PulseMouseMotionEvent> comp(world, "PulseMouseMotionEvent");
        ecs_id(PulseMouseMotionEvent) = comp.id();
        comp.member("x", &PulseMouseMotionEvent::x);
        comp.member("y", &PulseMouseMotionEvent::y);
        comp.member("is_touch", &PulseMouseMotionEvent::is_touch);
        comp.member(ecs_id(ecs_entity_t), "window", 0, offsetof(PulseMouseMotionEvent, window));
    }
}
