#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_app/idl/pulse_app.idl
// ============================================================================

#include <flecs.h>

#include "pulse_app.h"

inline void pulse_app_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseTimer> comp(world, "PulseTimer");
        ecs_id(PulseTimer) = comp.id();
        comp.member("delta_time", &PulseTimer::delta_time);
        comp.member("time_since_startup", &PulseTimer::time_since_startup);
        comp.member("delta_time_double", &PulseTimer::delta_time_double);
        comp.member("time_since_startup_double", &PulseTimer::time_since_startup_double);
        comp.member("fps", &PulseTimer::fps).range(0.0, 10000.0);
    }
}
