version(1)

typedef "bool"
typedef "char"
typedef "float"
typedef "double"
typedef "int8_t"
typedef "int32_t"
typedef "int64_t"
typedef "uint8_t"
typedef "uint16_t"
typedef "uint32_t"
typedef "uint64_t"
typedef "uintptr_t"
typedef "va_list"
typedef "void"
typedef "anyopaque"
typedef "size_t"
typedef "cstring"

enum.VfsResult { underscore, comment = "Pulse VFS operation result:" }
    .Ok
    .ErrorInvalidArgument
    .ErrorNotFound
    .ErrorBufferTooSmall
    .ErrorIO
    .ErrorInternal
    ()

enum.VfsSeekOrigin { underscore, comment = "Pulse VFS seek origin:" }
    .Set       --- Relative to the beginning of the stream
    .Current   --- Relative to the current read/write position
    .End       --- Relative to the end of the stream
    ()

enum.VfsPathType { underscore, comment = "Pulse VFS path type:" }
    .None       --- Path does not exist
    .File       --- A regular file
    .Directory  --- A directory
    .Other      --- Something else (device, socket, ...)
    ()

struct.VfsPathInfo
    .type   "VfsPathType::Enum"
    .size   "uint64_t"
    ()

struct.VfsDirEntry
    .name   "cstring"
    .type   "VfsPathType::Enum"
    ()

id "VfsFileId"
id "VfsDirId"

func.VfsAddContentRoot
    "VfsResult::Enum"
    .rootPath           "cstring"
    ()

func.VfsPathExists
    "bool"
    .path               "cstring"
    ()

func.VfsGetPathInfo
    "VfsResult::Enum"
    .path               "cstring"
    .outInfo            "*VfsPathInfo"
    ()

func.VfsOpenFile
    "?VfsFileId"
    .path               "cstring"
    .mode               "cstring"
    ()

func.VfsReadFile
    "VfsResult::Enum"
    .file               "VfsFileId"
    .buffer             "*anyopaque"
    .maxBytes           "size_t"
    .outRead            "*size_t"
    ()

func.VfsWriteFile
    "VfsResult::Enum"
    .file               "VfsFileId"
    .buffer             "*const anyopaque"
    .size               "size_t"
    ()

func.VfsSeekFile
    "VfsResult::Enum"
    .file               "VfsFileId"
    .offset             "int64_t"
    .origin             "VfsSeekOrigin::Enum"
    ()

func.VfsTellFile
    "int64_t"
    .file               "VfsFileId"
    ()

func.VfsGetFileSize
    "VfsResult::Enum"
    .file               "VfsFileId"
    .outSize            "*uint64_t"
    ()

func.VfsCloseFile
    "void"
    .file               "VfsFileId"
    ()

func.VfsOpenDir
    "?VfsDirId"
    .path               "cstring"
    ()

func.VfsReadDir
    "?*VfsDirEntry"
    .dir                "VfsDirId"
    ()

func.VfsCloseDir
    "void"
    .dir                "VfsDirId"
    ()