version(1)

typedef "bool"
typedef "char"
typedef "float"
typedef "double"
typedef "int8_t"
typedef "int32_t"
typedef "int64_t"
typedef "uint8_t"
typedef "uint16_t"
typedef "uint32_t"
typedef "uint64_t"
typedef "uintptr_t"
typedef "va_list"
typedef "void"
typedef "anyopaque"
typedef "size_t"
typedef "cstring"

--- From pulse_app.h
typedef "EPulseAppAddPluginResult"
typedef "PulseAppId"

const_value.VfsPluginDescVersion { value = "1u" }

--- Pulse VFS error codes, aligned with PHYSFS_ErrorCode.
enum.VfsErrorCode { underscore, comment = "Pulse VFS error codes:" }
    .Ok
    .OtherError
    .OutOfMemory
    .NotInitialized
    .IsInitialized
    .Argv0IsNull
    .Unsupported
    .PastEof
    .FilesStillOpen
    .InvalidArgument
    .NotMounted
    .NotFound
    .SymlinkForbidden
    .NoWriteDir
    .OpenForReading
    .OpenForWriting
    .NotAFile
    .ReadOnly
    .Corrupt
    .SymlinkLoop
    .IO
    .Permission
    .NoSpace
    .BadFilename
    .Busy
    .DirNotEmpty
    .OSError
    .Duplicate
    .BadPassword
    .AppCallback
    ()

--- Pulse VFS file type, aligned with PHYSFS_FileType.
enum.VfsFileType { underscore, comment = "Pulse VFS file type:" }
    .Regular    --- A normal file
    .Directory  --- A directory
    .Symlink    --- A symbolic link
    .Other      --- Something completely different like a device
    ()

--- Result returned by VfsEnumerateCallback, aligned with PHYSFS_EnumerateCallbackResult.
enum.VfsEnumerateResult { underscore, comment = "Pulse VFS enumerate callback result:" }
    .Error { value = -1 }   --- Stop enumerating, report error to app
    .Stop  { value = 0 }    --- Stop enumerating, report success to app
    .Ok    { value = 1 }    --- Keep enumerating, no problems
    ()

--- Metadata for a file or directory, aligned with PHYSFS_Stat.
struct.VfsStat
    .fileSize   "int64_t"
    .modTime    "int64_t"
    .createTime "int64_t"
    .accessTime "int64_t"
    .fileType   "VfsFileType::Enum"
    .readOnly   "bool"
    ()

--- Plugin descriptor
struct.VfsPluginDesc
    .structSize "uint32_t"
    .version    "uint32_t"
    ()

id "VfsFileId"

--- Callback for enumeration, aligned with PHYSFS_EnumerateCallback.
funcptr.VfsEnumerateCallback
    "VfsEnumerateResult::Enum"
    .data       "?*anyopaque"
    .origDir    "cstring"
    .fname      "cstring"
    ()

func.VfsPluginDescDefault
    "VfsPluginDesc"
    ()

func.AddVfsPlugin
    "EPulseAppAddPluginResult"
    .app    "PulseAppId"
    .desc   "*const VfsPluginDesc"
    ()

func.VfsMount
    "bool"
    .newDir         "cstring"
    .mountPoint     "?cstring"
    .appendToPath   "bool"
    ()

func.VfsUnmount
    "bool"
    .oldDir     "cstring"
    ()

func.VfsGetWriteDir
    "?cstring"
    ()

func.VfsSetWriteDir
    "bool"
    .newDir     "?cstring"
    ()

func.VfsExists
    "bool"
    .fname      "cstring"
    ()

func.VfsStat
    "bool"
    .fname      "cstring"
    .stat       "*VfsStat"
    ()

func.VfsOpenRead
    "?VfsFileId"
    .filename   "cstring"
    ()

func.VfsOpenWrite
    "?VfsFileId"
    .filename   "cstring"
    ()

func.VfsOpenAppend
    "?VfsFileId"
    .filename   "cstring"
    ()

func.VfsClose
    "bool"
    .file       "VfsFileId"
    ()

func.VfsReadBytes
    "int64_t"
    .file       "VfsFileId"
    .buffer     "*anyopaque"
    .len        "uint64_t"
    ()

func.VfsWriteBytes
    "int64_t"
    .file       "VfsFileId"
    .buffer     "*const anyopaque"
    .len        "uint64_t"
    ()

func.VfsEof
    "bool"
    .file       "VfsFileId"
    ()

func.VfsTell
    "int64_t"
    .file       "VfsFileId"
    ()

func.VfsSeek
    "bool"
    .file       "VfsFileId"
    .pos        "uint64_t"
    ()

func.VfsFileLength
    "int64_t"
    .file       "VfsFileId"
    ()

func.VfsEnumerate
    "bool"
    .dir        "cstring"
    .callback   "VfsEnumerateCallback"
    .userData   "?*anyopaque"
    ()

func.VfsGetLastErrorCode
    "VfsErrorCode::Enum"
    ()

func.VfsGetErrorByCode
    "?cstring"
    .code       "VfsErrorCode::Enum"
    ()
