// ============================================================================
// package_register.cpp
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/gen_package_register/generate.lua
// Source: src/pulse_font/idl/pulse_font.idl
// ============================================================================
#include "pulse_config.h"
#include "pulse_font.h"

extern "C" {

    PULSE_FONT_API EPulseResult pulse_package_register(PulseAppId app, PulseConfig* config) {
    PulseFontPluginDesc desc = pulse_font_plugin_desc_default();
    if (config) {
        desc.atlas_width = (uint32_t)pulse_config_get_int(config, "atlas_width", desc.atlas_width);
        desc.atlas_height = (uint32_t)pulse_config_get_int(config, "atlas_height", desc.atlas_height);
        desc.max_atlas_count = (uint32_t)pulse_config_get_int(config, "max_atlas_count", desc.max_atlas_count);
        desc.sdf_padding = (uint32_t)pulse_config_get_int(config, "sdf_padding", desc.sdf_padding);
        desc.record_priority = (int32_t)pulse_config_get_int(config, "record_priority", desc.record_priority);
    }
    EPulseAppAddPluginResult r = pulse_add_font_plugin(app, &desc);
    switch (r) {
        case PULSE_APP_ADD_PLUGIN_RESULT_OK: return PULSE_RESULT_OK;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT: return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_STATE: return PULSE_RESULT_ERROR_INVALID_STATE;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN: return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_PLUGIN_BUILD_FAILED: return PULSE_RESULT_ERROR_INTERNAL;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INTERNAL: return PULSE_RESULT_ERROR_INTERNAL;
        default: return PULSE_RESULT_ERROR_INTERNAL;
    }
}
} // extern "C"
