// ============================================================================
// package_register.cpp
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/gen_package_register/generate.lua
// Source: src/pulse_transform/idl/pulse_transform.idl
// ============================================================================
#include "pulse_config.h"
#include "pulse_transform.h"

extern "C" {

    PULSE_TRANSFORM_API EPulseResult pulse_package_register(PulseAppId app, PulseConfig* config) {
    if (config) {
        return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
    }
    EPulseAppAddPluginResult r = pulse_add_transform_plugin(app);
    switch (r) {
        case PULSE_APP_ADD_PLUGIN_RESULT_OK: return PULSE_RESULT_OK;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_ARGUMENT: return PULSE_RESULT_ERROR_INVALID_ARGUMENT;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INVALID_STATE: return PULSE_RESULT_ERROR_INVALID_STATE;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_DUPLICATE_PLUGIN: return PULSE_RESULT_ERROR_DUPLICATE_PLUGIN;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_PLUGIN_BUILD_FAILED: return PULSE_RESULT_ERROR_INTERNAL;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_MISSING_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY: return PULSE_RESULT_ERROR_CIRCULAR_PLUGIN_DEPENDENCY;
        case PULSE_APP_ADD_PLUGIN_RESULT_ERROR_INTERNAL: return PULSE_RESULT_ERROR_INTERNAL;
        default: return PULSE_RESULT_ERROR_INTERNAL;
    }
}
} // extern "C"
