#pragma once

// ============================================================================
// GENERATED FILE - DO NOT EDIT.
//
// Generated by tools/idl generate-binding.lua (binding: flecs)
// Source: src/pulse_transform/idl/pulse_transform.idl
// ============================================================================

#include <flecs.h>

#include "pulse_transform.h"

inline void pulse_transform_register_reflection(ecs_world_t* world) {
    {
        flecs::component<PulseLocalTransform> comp(world, "PulseLocalTransform");
        ecs_id(PulseLocalTransform) = comp.id();
        comp.member("translation", &PulseLocalTransform::translation);
        comp.member("rotation", &PulseLocalTransform::rotation);
        comp.member("scale", &PulseLocalTransform::scale);
    }
    {
        flecs::component<PulseWorldTransform> comp(world, "PulseWorldTransform");
        ecs_id(PulseWorldTransform) = comp.id();
        comp.member("value", &PulseWorldTransform::value);
    }
    {
        flecs::component<PulseShowMatrix> comp(world, "PulseShowMatrix");
        ecs_id(PulseShowMatrix) = comp.id();
        comp.member("model", &PulseShowMatrix::model);
    }
}
